//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualAdvisorDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendar
    {
        public int CalendarId { get; set; }
        public int UniversityId { get; set; }
        public string EventTypeId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<bool> AllDay { get; set; }
        public string CalendarDescription { get; set; }
    
        public virtual EventType EventType { get; set; }
        public virtual University University { get; set; }
    }
}
