//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualAdvisorDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrollmentGrade
    {
        public int EnrollmentId { get; set; }
        public int StaffId { get; set; }
        public int CreditHoursAttempted { get; set; }
        public int CreditHoursEarned { get; set; }
        public string Grade { get; set; }
    
        public virtual Enrollment Enrollment { get; set; }
    }
}
