//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualAdvisorDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectionRating
    {
        public int RatingId { get; set; }
        public int SectionId { get; set; }
        public string RatingScaleId { get; set; }
        public Nullable<System.DateTime> RatingDate { get; set; }
        public string Comments { get; set; }
    
        public virtual Section Section { get; set; }
        public virtual SectionRatingScale SectionRatingScale { get; set; }
    }
}
