//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualAdvisorDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public int UserDetailsId { get; set; }
        public int StudentId { get; set; }
        public string SkypeId { get; set; }
        public Nullable<int> Passcode { get; set; }
        public string AppType { get; set; }
    }
}
